// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIXEAFwZXgLTwnKwausToqcLshtkfOQ8',
    appId: '1:27146247483:web:6c961f7cd3c421b04e2b1e',
    messagingSenderId: '27146247483',
    projectId: 'django-fcm-b9b58',
    authDomain: 'django-fcm-b9b58.firebaseapp.com',
    storageBucket: 'django-fcm-b9b58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoJ5CRjZ3zNBl0VxfBA3hA8vBDpLOOTh8',
    appId: '1:27146247483:android:165af8a972fcc2e44e2b1e',
    messagingSenderId: '27146247483',
    projectId: 'django-fcm-b9b58',
    storageBucket: 'django-fcm-b9b58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtkmVXaJs4s8w99PtmsvpcbNa0I3aG6ow',
    appId: '1:27146247483:ios:fa77c1684bc69fc74e2b1e',
    messagingSenderId: '27146247483',
    projectId: 'django-fcm-b9b58',
    storageBucket: 'django-fcm-b9b58.appspot.com',
    iosBundleId: 'com.example.getFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtkmVXaJs4s8w99PtmsvpcbNa0I3aG6ow',
    appId: '1:27146247483:ios:e459ae5e24bbf3824e2b1e',
    messagingSenderId: '27146247483',
    projectId: 'django-fcm-b9b58',
    storageBucket: 'django-fcm-b9b58.appspot.com',
    iosBundleId: 'com.example.getFcm.RunnerTests',
  );
}
